### ISSUE TITLE
PIO is moving to be a required dependency for CESM so included and built outside of CESM

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/mizuRoute#296]
There is a move where PIO won't be included as part of CESM, and it will be required to be built outside of CESM (much like how NetCDF is handled now). This might change how we handle the stand-alone build for mizuRoute, we likely will have to point to an explicit version of PIO.

Definition of done:
- Allow stand-alone build to use a pre-built PIO library

**Comment by ekluzek** [comment]
This might be something you want to change in the standalone build as well. But, the current process of building PIO as an external to standalone mizuRoute should continue to work.

**Comment by ekluzek** [comment]
This is essentially what we talked about with @ShervanGharari and @nmizukami today. We want the ability to use a pre-built library as well as one that the user builds as part of the mizuRotue build.

**Comment by nmizukami** [comment]
PR #459 allow a user to use system installed PIO instead of building PIO in mizuRoute standalone building process. However, if system installed PIO does not have GPTL option, the mizuRoute does not run...   

One way to solve this is to link GPTL library (which is still not implemented), or make GPTL calls is optional (some control in mizuRoute code).

We recommend building PIO together with mizuRoute is way to go for standalone.
